/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package commint_lint_jira;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'commint_lint_jira.greeting' plugin.
 */
public class CommintLintJiraPluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("commitlintPlugin");
				// CommitLintJiraPlugin commitLintJiraPlugin = project.getPlugins().findPlugin(CommitLintJiraPlugin.class);
				// commitLintJiraPlugin.apply(project);

        // Verify the result
        assertNotNull(project.getTasks().findByName("commitlintPlugin"));
    }
}
