/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package commint_lint_jira;

import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.provider.Property;

/**
 * A simple 'hello world' plugin.
 */
public class CommitLintJiraPlugin implements Plugin<Project> {

  public void apply(Project project) {
    // Register a task
    CommitLintJiraRestModel extension = project
      .getExtensions()
      .create("commitlintPlugin", CommitLintJiraRestModel.class);

    project
      .getTasks()
      .register(
        "validateCommitMessage",
        CommitLintJiraPluginTask.class,
        task -> {
          task.getUser().set(extension.getUser());
          task.getPassword().set(extension.getPassword());
          task.getDomain().set(extension.getDomain());
          task.getUrl().set(extension.getUrl());
        }
      );
  }
}

interface CommitLintJiraRestModel {
  Property<String> getUser();
  Property<String> getPassword();
  Property<String> getDomain();
  Property<String> getUrl();
}
