/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package commint_lint_jira.dto;

/**
 * A simple 'hello world' plugin.
 */
public class CommitLintJiraRestModel  {

	private String user;
	private String password;
	private String domain;
	private String url;
    
	public CommitLintJiraRestModel(String user, String pass, String domain, String url) {
		this.user=user;
		this.password=pass;
		this.domain=domain;
		this.url=url;
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDomain() {
		return domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	
}
